apiVersion: v1
kind: Pod
metadata:
  name: redispod
  namespace: web
spec:
  containers:
  - image: redis
    name: redis
    ports:
    - containerPort: 9090
      name: redispod
      protocol: TCP
